name: "Analisi Profonda "
on: [push]
jobs:
  deep-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4'
      - name: Esecuzione Analisi
        run: |
          agda --cubical --safe Verifica_Analisi_Profonda.agda
